---
title: "1_Background"
author: "Aimee Steinwand"
date: "2026-02-09"
output: pdf_document
---

This project is a secondary data analysis of the Multicenter AIDS Cohort Study, an ongoing prospective cohort study of the natural and treated histories of HIV-1 infection in homosexual and bisexual men in 4 major cities in the United States. 


Highly active antiretroviral treatment (HAART) is the standard treatment for HIV infected patients.  Our dataset includes up to 8 years of longitudinal laboratory and quality of life measures, as well as demographic and other health information, on HIV infected men after beginning HAART.  The subjects were seen annually.  Year 0 data are from the subjects’ last untreated visit, just before beginning HAART.  All other visits (year 1 up to 8) are on treatment.  


# Question of Interest: 
We are interested in understanding how treatment response 2 years after initiating HAART differs between subjects who report using hard drugs, such as heroine and cocaine, at baseline and other subjects, who did not report hard drug use at baseline. 



# Biologic Motivation: 
There is limited evidence from laboratory in vitro and animal studies that the use of hard drugs inhibits the immune system and increases HIV replication; however, results have not been clear in human studies.  If drug users have poor treatment response compared to others, we may need to consider more aggressive treatment strategies or more actively encourage patients to enroll in drug rehabilitation programs.



# Information about variables: 
We have 4 measures of treatment response.  
The first two are laboratory measures, 
- viral load (VLOAD), which is the number of HIV copies in a mL of blood, and 
- the second is CD4+ T cell count (LEU3N), a measure of immunologic health.  

In untreated HIV infection, viral load increases over time and CD4+ T cell counts decline as the immune system is attacked by the virus.  

Once treatment is initiated, we expect viral load to decrease rapidly and CD4 counts to recover.  

Our last two measures are quality of life measures from the SF-36.  
- The first is the aggregate physical quality of life score (AGG_PHYS) and 
- the second is the aggregate mental quality of life score (AGG_MENT).  

These scores range from 0 to 100, with higher scores indicating better quality of life.  

We are not sure what happens to quality of life after initiating treatment - while in theory subjects’ improving health should result in increased quality of life, the side effects of these treatments are significant.  If subjects experience declines in quality of life after initiating treatment we would be concerned that they would stop treatment.

Some of our colleague’s statistical team has been doing their analysis Bayesian.  We are requesting that the analysis be done in both a Bayesian and non-Bayesian framework and compared.


# Questions for PI

Only interested in hard drugs at baseline? Year 0, not concerenced about year 1 and year 2 users

All model adjustments
- age, bmi, smoking, education, race/ethnicity, adherence

Adherence
- if there is a difference in 

Hard drug use could influence medication adherence, any differences in outcomes for hard drug users versus not hard drug users explain adherence issues

Biologically implausible or assay limits?
- Ranges are in data dictionary, can bring up any outliers

 Drug use Refuse to answer
- technically missing

CD4 T-cell counts: 
Viral load: treated near zero, untreated all over
QoL: 1-100

# Initial Data Analysis Plan

Simple linear regression
- 4 models: viral load, CD4+ T cell count, Physical Quality of Life, Mental Quality of life
- age, bmi, smoking, education, race/ethnicity, adherence
- 


Bayesian Analysis
- DIC, WAIC, LOO-CV, second two recommended more vs first checking MCMC
- loo package has function loo
- waic function
- DIC have to calculate by hand



# Analysis Presentation Notes

- Bayesian trace plots 4MCM chains 4k iterations
- Separate files for exploratory vs final analysis for code

- Adherence - could outcomes be related to adherence, stratified by drug use???
fit models with adherence and without adherence and then compare the models


- Table 1 notes negative BMIs and exceeding 250, missing values for outcomes and covariates
matched baseline visits to year 2 visits
Label that includes information that missing has been removed prior to Table 1

- Missingness for outcomes if they are missing ANY outcomes remove them from the whole dataset so they have all 4 outcomes at year 2 so consistent n values for each analysis

- Race/Ethnicity - Non-hispanic white and other
- Education - 4 years of college/college degree and then below (2 groups)
- log10 viral load! Woot already did that. Gold star to me


Clinically meaningful outcomes
- viral load 0.5log10 change
- cd4 count 50 cell change - expect CD4 counts to go up 
- QoL scores 2 point change


Reproducible Research - Ella
- announcement on canvas
- start labeling commits with which project to track easier
- create separate files for final versions of code

# Notes from P0 to bring into P1
- Not enough detail in the methods
- justify and explain modeling choices
- why choose different variables
- if you are removing or excluding why are you removing, which model are they removed from
- keeping track of sample size: how many observations and subjects were used for each analysis/model
- tables/figures: captions and legends with descriptive labels, 
flow charts to show exclusions for ppt and appendix
Table 1 you absolute idiot!! 

- point estimates





















