---
title: "Project 0"
author: "Aimee Steinwand"
date: "2026-01-26"
output: html_document
---

Background: 

Cortisol and DHEA are two hormones that regulate our stress system. Cortisol is known to have a peak shortly after waking and then falls over
the day to a low in the evening. Features of this diurnal pattern have been implicated in depression, sleep disorders and many other
conditions. Being able to collect samples to measure this curve in a natural environment (e.g. at home) is useful for research on this
endocrine system. The accuracy of saliva sample collection is crucial to obtaining reliable characterization of the cortisol awakening response
and perhaps defining the diurnal decline in salivary cortisol. 


Investigator's Research Question: 

We tested the use of a convenient and novel collection device for collecting saliva on strips of filter paper in a specially constructed
booklet for determination of both salivary cortisol and DHEA.  In the present study, 31 healthy control subjects collected saliva samples
four times a day for three days using the filter paper device (Saliva Procurement and Integrated Testing (SPIT) booklet) which was maintained
during the collection period in a large plastic bottle with an electronic monitoring cap. Subjects were asked to collect saliva samples at
waking, 30 min later, before lunch and 600 min after waking.  The time of waking and the time before lunch were allowed to vary by the
subjects’ schedules.


Our questions are: 
1) what is the agreement between the subject’s recordings of sampling times compared to the times recorded by an electronic monitoring cap?, 

2) are subjects adhering accurately to the +30min and +10 hour sampling times required by a study protocol?, 

3) what are the changes of cortisol and DHEA over time?


Investigator Questions:
	- How was missingness handled? Time recorded but no value
		○ Some problems at the lab where they couldn't analyze the sample provided
		○ If user forgot to put the cap back on the electronic bottle, might have missing times for samples
	- Time since they reported waking up, not time in between samples interval
	- 999 means missing
	- Cortisol established
		○ Spikes after waking up about 30min, then slowly decreases throughout the day 
		○ Looking at can we catch the spike at 30min and then what is the rate of decline?
		○ Use: Cortisol (nmol/L)
	- Test of association to see if there is any association or bias for 1.
	- For Question 2 time intervals the investigator cares about
		○ For adherence how close are they to the 30min and 10 hour time frame?
		○ Good adherence is within 7.5min plus or minus 
		○ Adequate adherence is within 15min plus or minus
	- Cortisol levels
		○ Over 26, possible but not likely, don't remove
		○ Over 80, laboratory error 
	- DHEA
		○ Upper limit of the assay: 5.205. Super high, likely an error, unless a person was recording it consistently, still exclude because might have something else going on
	- Analyze individual data points within the model not average over the missing ones
	
	
Summary of Notes from Class:
General questions and comments:
The investigator stated that the sample.interval variables are the times between first booklet (and first cap) recorded time and subsequent recorded samples. The investigator said she was not sure these were calculated correctly and that she was not interested in using these values in analysis.
Rather, she said she is interested in measuring booklet and cap time since waking, where wake time is determined from the sleep diary.

Missing data:
DHEA and cortisol measurements may be missing even if a booklet or cap time is recorded due to lab errors or insufficient sample collection/poor sample quality.
Cap times can be missing even if a booklet time is recorded. This could be due to cap malfunction (low battery) or due to user error (they forgot to put the booklet back in the bottle before taking the next sample).
The investigator is interested in knowing about the rates of missing data in your report.

For question 1, what is meant by agreement?
The investigator said she imagined a scatter plot showing the correlation between time since waking measured using the booklet vs. the cap and wanted to know if the two measures were significantly associated. She said she was interested to know if there was any bias/if the booklet times tended to be recorded earlier or later or at about the same as the cap times.

For question 2, what is meant by adherence?
The investigator stated that she wanted to consider adherence in two ways.
The percentage of samples taken within 7.5 minutes of the scheduled time.
The percentage of samples within 15 minutes of the scheduled time.

For question 3:
Which DHEA and cortisol measurements should be used?
The nmol/L measures.

What is the expected range of cortisol and DHEA?
Cortisol: values over 26 are high, but biologically possible. Values over 80 are likely lab errors and should be excluded.

DHEA: there is an upper detection limit to the assay (5.205). This corresponds to an extremely high DHEA level and since the level is not observed, it could make it difficult to see the diurnal patterns of DHEA change over the course of the day.  These observations should be excluded.  The investigator also said that if any participants had several DHEA measures at the detection limit, they could have underlying health problems and that she would want to exclude that person from Q3 analysis. She asked that you let her know if you found any participants like this.

What are the patterns of change over the course of the day? What is the investigator interested in knowing about changes over time?
The investigator stated that levels of cortisol and DHEA are expected to increase sharply from waking to 30 minutes after waking and then decline more slowly over the rest of the day.
She was interested in knowing if the SPIT test shows this expected pattern.
She wanted to know: 
1) is there an increase in cortisol and/or DHEA from waking to 30 minutes post waking? And 
2) what is the rate of decline in cortisol and DHEA after 30 minutes from waking?
She also stated that even if there are not statistically significant differences, she would like to know the estimates for the initial increase and rates of decline so she can compare them to what is known from other more standard hormone tests.

Which time measurement should be used for this analysis (Cap or Booklet)?
The investigator said she thought the two time measures should agree and therefore either would be fine. She asked us to choose whichever we thought would be best for statistical reasons.


Analysis Plans:

	1) Mixed effects model - explain bias and correlation/association
		a. Cap time missing can only calculate for ones you have the pair - different rates of missingness for each group 
	2) Booklet time - Good, adequate, bad adherence
What percent of people make it within the 7.5min window and what percent make it within the 15min window


Variable definitions:
Subjectid: Subject number
CollectionDate: Date of sample collection formatted as mm/dd/yyyy
Collection Sample: ordering of samples over the day ranging from 1-4. 1 is at waking, 2 ~30 min from waking, 3 at ~lunch and 4 at ~10 hours after waking.

Booklet: Clock time: Time of day of sample collection noted by participant formatted as hh:mm in military time.
MEMs: Clock time: Time of day of sample collection by electronic cap stamp formatted as hh:mm in military time.
Sleep Diary reported wake time: Time of day of waking formatted as hh:mm in military time.
Booklet: Sample interval: Number of hours and minutes from waking recorded by participant formatted as hh:mm where waking was recorded as midnight 00:00
Booklet: Sample interval Decimal Time (mins): Number of minutes from waking for the sample as recorded by participant.

MEMs: Sample interval: Number of hours and minutes from waking electronic cap stamp formatted as hh:mm where waking was recorded as midnight 00:00
MEMs: Sample interval Decimal Time (mins): Number of minutes from waking electronic stamp.

Cortisol (ug/dl): Cortisol levels in nanograms/deciliter units.
DHEA (pg/dl): DHEA levels in picograms/deciliter units.
Cortisol (nmol/L): Cortisol levels in a different unit.
DHEA (nmol/L): DHEA levels in a different unit.
DAYNUMBER: Number of the day samples were collected. 1-3 days.






